version: 2.1

orbs:
  hmpps: ministryofjustice/hmpps@9

jobs:
  validate:
    executor:
      name: hmpps/java
      tag: "21.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run:
          command: ./gradlew check
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - store_test_results:
          path: hmpps-kotlin-spring-boot-autoconfigure/build/test-results
      - store_artifacts:
          path: hmpps-kotlin-spring-boot-autoconfigure/build/reports/tests
      - store_test_results:
          path: hmpps-kotlin-spring-boot-test-autoconfigure/build/test-results
      - store_artifacts:
          path: hmpps-kotlin-spring-boot-test-autoconfigure/build/reports/tests
      - store_test_results:
          path: test-app/build/test-results
      - store_artifacts:
          path: test-app/build/reports/tests
      - store_test_results:
          path: test-app-reactive/build/test-results
      - store_artifacts:
          path: test-app-reactive/build/reports/tests
      - persist_to_workspace:
          root: .
          paths:
            - hmpps-kotlin-spring-boot-autoconfigure/build/libs
            - hmpps-kotlin-spring-boot-starter/build/libs
            - hmpps-kotlin-spring-boot-test-autoconfigure/build/libs
            - hmpps-kotlin-spring-boot-starter-test/build/libs
            - build.gradle.kts

  publish:
    executor:
      name: hmpps/java
      tag: "21.0"
    steps:
      - checkout
      - restore_cache:
          keys:
            - gradle-{{ checksum "build.gradle.kts" }}
            - gradle-
      - run: |
            ORG_GRADLE_PROJECT_signingKey=$(echo -e "$ORG_GRADLE_PROJECT_signingKey")
            ./gradlew publishToSonatype closeAndReleaseSonatypeStagingRepository
      - save_cache:
          paths:
            - ~/.gradle
          key: gradle-{{ checksum "build.gradle.kts" }}
      - persist_to_workspace:
          root: .
          paths:
            - build.gradle.kts

workflows:
  version: 2
  build-and-test:
    jobs:
      - validate:
          filters:
            tags:
              ignore: /.*/
      - publish-approval:
          type: approval
          requires:
            - validate
          filters:
            branches:
              only:
                - main
      - publish:
          requires:
            - publish-approval
          filters:
            branches:
              only:
                - main
